services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
#    command: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --workers=2 --bind 0.0.0.0:8000 kittens.wsgi
#    command: gunicorn --workers=2 --bind 0.0.0.0:8000 kittens.wsgi
#    command: python manage.py collectstatic --noinput && gunicorn --workers=2 --bind 0.0.0.0:8000 kittens.wsgi




    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env

volumes:
  postgres_data:
