# Generated by Django 4.2.4 on 2024-10-02 10:20

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Breed = apps.get_model('exhibition', 'Breed')
    Kitten = apps.get_model('exhibition', 'Kitten')
    Rating = apps.get_model('exhibition', 'Rating')
    User = apps.get_model('auth', 'User')

    owner = User.objects.create_user(username='owner', password='somepassword', email='owner@test.com')
    guest = User.objects.create_user(username='guest', password='somepassword', email='guest@test.com')

    breed1 = Breed.objects.create(name='Scottish Fold')
    breed2 = Breed.objects.create(name='Maine Coon')
    breed3 = Breed.objects.create(name='Persian')

    kitten1 = Kitten.objects.create(breed=breed1, owner=owner, color='grey', age_months=3, description='cat')
    kitten2 = Kitten.objects.create(breed=breed2, owner=owner, color='black', age_months=4, description='cat2')
    kitten3 = Kitten.objects.create(breed=breed3, owner=owner, color='white', age_months=5, description='cat3')

    Rating.objects.create(kitten=kitten1, user=guest, score=5)
    Rating.objects.create(kitten=kitten2, user=guest, score=5)
    Rating.objects.create(kitten=kitten3, user=guest, score=5)


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_rating'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
